<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-17 20:46
=======
# Generated by Django 3.2.8 on 2021-10-19 03:21
>>>>>>> dc470303bf4b28221614af9800d5dea6727be939

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("price", models.PositiveIntegerField(null=True)),
                ("active", models.BooleanField(default=True)),
<<<<<<< HEAD
                ("category", models.ManyToManyField(blank=True, to="product.category")),
=======
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="product.Category"),
                ),
>>>>>>> dc470303bf4b28221614af9800d5dea6727be939
            ],
        ),
    ]
