<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-17 20:46
=======
# Generated by Django 3.2.8 on 2021-10-19 03:21
>>>>>>> dc470303bf4b28221614af9800d5dea6727be939

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
>>>>>>> dc470303bf4b28221614af9800d5dea6727be939
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("product", models.ManyToManyField(to="product.product")),
=======
                ("product", models.ManyToManyField(to="product.Product")),
>>>>>>> dc470303bf4b28221614af9800d5dea6727be939
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
