name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
        python-version: [3.8, 3.9]
=======
        python-version: [3.12]
>>>>>>> f7c294766804d6077e22a61d40c5fcdba9c96cbd

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
<<<<<<< HEAD

=======
>>>>>>> f7c294766804d6077e22a61d40c5fcdba9c96cbd
    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
<<<<<<< HEAD
      run: python -m poetry install
=======
      run: | 
        python -m poetry lock
        python -m poetry install
>>>>>>> f7c294766804d6077e22a61d40c5fcdba9c96cbd

    - name: Test
      run: |
        poetry run python manage.py test